site_name: CCI - Claude Code IDE
site_description: A git worktree-first IDE with prompt-driven patch workflow
site_author: Claude Code
site_url: https://example.com/cci

repo_name: cci
repo_url: https://github.com/example/cci

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    # Light mode
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/code-braces

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
  - mermaid2:
      version: '10.6.0'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quickstart.md
  - User Guide:
      - Overview: user-guide/overview.md
  - Development:
      - Status: STATUS.md
      - Progress: PROGRESS.md
      - Testing: TESTING.md
      - UAT Ready: UAT_READY.md
      - Issues: ISSUES.md
      - Current Sprint: development/CURRENT_SPRINT.md
      - Decisions: development/DECISIONS.md
      - Feature Log: development/FEATURE_LOG.md
      - TODO: development/TODO.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/example/cci
  version:
    provider: mike

copyright: |
  &copy; 2025 Claude Code by Anthropic